---
title           : "Character displacement of bill ratio in penguins of the Palmer Archipelago"
shorttitle      : "Character displacement in penguins"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Lucas Eckert
    affiliation : 1

affiliation:
  - id          : 1
    institution : McGill University, Montreal, QC, Canada
    
csl: "../05_references/ecology-letters.csl"

bibliography: ["../05_references/grateful-refs.bib"]

output: prereg::prereg_pdf
---

```{r, include=F}
library(prereg)
```

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

**Yes**, this project uses data that have already been collected and are publicly available. The data will be accessed through the palmerpenguins R package [@palmerpenguins].

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

Interspecific competition for prey should result in character displacement of trophic traits, like bill morphology.

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

**Bill ratio**, defined as the ratio between bill depth and length.

## Independent variable

<!-- How many and which conditions will participants be assigned to? -->

**Species**, treated as a factor with three levels: Adelie, Chinstrap, and Gentoo.

## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

Pairwise T-tests (with a multiple testing correction) to test for significant differences in mean bill ratio among species.

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

We will not exclude any purely statistical outliers without confirming with the collectors of the data that those data represent an error or anomaly that should be excluded.

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

Data exist on **344 penguins**, with roughly equal proportions of each species.

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

Nothing else to preregister.

## Study type

-   Class project or assignment
-   Experiment
-   Survey
-   **Observational/archival study**
-   Other:

# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
